# url: "https://mysite.github.io" # the base hostname & protocol for your site
baseurl: ""                     # the subpath of your site, e.g. /blog/
baseurl_images: "/ptm-images/"
#...
title: Paint The Mouse
banner_image: /ptm-images/water/water-7.jpg
author:
  name:           	 Ray Murphy
disqus_shortname: 'paintthemouse' # ignore this if not using Disqus
# keep_files: []
exclude: ["_app",
          "Gemfile",
          "Gemfile.lock",
          "config.codekit3"] # Don't forget that Jekyll automatically
                          # excludes files with a dot prefix
compress_html:
  blanklines: true
